services:
  mariadb:
    build:
      context: requirements/mariadb
    image: mariadb:chdonnat42
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception

  wordpress:
    build:
      context: requirements/wordpress
    image: wordpress:chdonnat42
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - "9000"
    networks:
      - inception

  nginx:
    build:
      context: requirements/nginx
    image: nginx:chdonnat42
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  static-site:
    build:
      context: requirements/bonus/static-site
    image: static-site:chdonnat42
    container_name: static-site
    env_file: .env
    expose:
      - "80"
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ~/chdonnat/data/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ~/chdonnat/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge